#undef __uint64_t
#undef ss_size
#undef __P
#undef __CONCAT
#undef __always_inline
#undef __nonnull
#undef INT8_C
#undef INT16_C
#undef INT32_C
#undef UINT8_C
#undef UINT16_C
#undef UINT32_C
#undef INT64_C
#undef UINT64_C
#undef INTMAX_C
#undef UINTMAX_C
#undef INT8_MIN
#undef INT16_MIN
#undef INT32_MIN
#undef INT8_MAX
#undef INT16_MAX
#undef INT32_MAX
#undef UINT8_MAX
#undef UINT16_MAX
#undef UINT32_MAX
#undef INT64_MIN
#undef INT64_MAX
#undef UINT64_MAX
#undef INT_LEAST8_MIN
#undef INT_LEAST16_MIN
#undef INT_LEAST32_MIN
#undef INT_LEAST64_MIN
#undef INT_LEAST8_MAX
#undef INT_LEAST16_MAX
#undef INT_LEAST32_MAX
#undef INT_LEAST64_MAX
#undef UINT_LEAST8_MAX
#undef UINT_LEAST16_MAX
#undef UINT_LEAST32_MAX
#undef UINT_LEAST64_MAX
#undef INT_FAST8_MIN
#undef INT_FAST16_MIN
#undef INT_FAST32_MIN
#undef INT_FAST64_MIN
#undef INT_FAST8_MAX
#undef INT_FAST16_MAX
#undef INT_FAST32_MAX
#undef INT_FAST64_MAX
#undef UINT_FAST8_MAX
#undef UINT_FAST16_MAX
#undef UINT_FAST32_MAX
#undef UINT_FAST64_MAX
#undef INTPTR_MIN
#undef INTPTR_MAX
#undef UINTPTR_MAX
#undef INTMAX_MIN
#undef INTMAX_MAX
#undef UINTMAX_MAX
#undef PTRDIFF_MIN
#undef PTRDIFF_MAX
#undef SIG_ATOMIC_MIN
#undef SIG_ATOMIC_MAX
#undef SIZE_MAX
#undef WINT_MIN
#undef WINT_MAX
